import Head from 'next/head'
import {Banner, Header, Row} from "../components";
import {apiRequest} from "../utils";
import {RootObject} from "../typings";

// interface IProps {
//     netflixOriginals: RootObject | Result[] | Movie[],
//     trendingNow: RootObject | Result[] | Movie[],
//     topRated: RootObject | Result[] | Movie[],
//     actionMovies: RootObject | Result[] | Movie[],
//     comedyMovies: RootObject | Result[] | Movie[],
//     horrorMovies: RootObject | Result[] | Movie[],
//     romanceMovies: RootObject | Result[] | Movie[],
//     documentaries: RootObject | Result[] | Movie[],
// }

interface IProps {
    netflixOriginals: RootObject,
    trendingNow: RootObject,
    topRated: RootObject,
    actionMovies: RootObject,
    comedyMovies: RootObject,
    horrorMovies: RootObject,
    romanceMovies: RootObject,
    documentaries: RootObject,
}

const Home = ({
                  netflixOriginals,
                  trendingNow,
                  topRated,
                  actionMovies,
                  comedyMovies,
                  horrorMovies,
                  romanceMovies,
                  documentaries,
              }: IProps) => {
    return (
        <div className={'relative h-screen bg-gradient-to-b lg:h-[140vh]'}>
            <Head>
                <title>Home - Oflix</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header/>
            <main className={'relative pl-4 pb-24 lg:space-y-3 lg:pl-10'}>
                <Banner netflixOriginals={netflixOriginals.value.results}/>
                <section className={'md:space-y-24'}>
                    <div className={'mt-12'}/>
                    {/*My list*/}
                    <Row title="Trending Now" movies={trendingNow.value.results}/>
                    <Row title="Top Rated" movies={topRated.value.results}/>
                    <Row title="Action Thrillers" movies={actionMovies.value.results}/>
                    <Row title="Comedies" movies={comedyMovies.value.results}/>
                    <Row title="Scary Movies" movies={horrorMovies.value.results}/>
                    <Row title="Romance Movies" movies={romanceMovies.value.results}/>
                    <Row title="Documentaries" movies={documentaries.value.results}/>
                </section>

                {/*Modal*/}
            </main>
        </div>
    )
}

export async function getServerSideProps() {
    try {
        const [
            netflixOriginals,
            trendingNow,
            topRated,
            actionMovies,
            comedyMovies,
            horrorMovies,
            romanceMovies,
            documentaries,
        ] = await Promise.allSettled([
            fetch(apiRequest.fetchNetflixOriginals).then((res) => res.json()),
            fetch(apiRequest.fetchTrending).then((res) => res.json()),
            fetch(apiRequest.fetchTopRated).then((res) => res.json()),
            fetch(apiRequest.fetchActionMovies).then((res) => res.json()),
            fetch(apiRequest.fetchComedyMovies).then((res) => res.json()),
            fetch(apiRequest.fetchHorrorMovies).then((res) => res.json()),
            fetch(apiRequest.fetchRomanceMovies).then((res) => res.json()),
            fetch(apiRequest.fetchDocumentaries).then((res) => res.json()),
        ])
        console.error(`Success. Fetching from api`)

        return {
            props: {
                netflixOriginals,
                trendingNow,
                topRated,
                actionMovies,
                comedyMovies,
                horrorMovies,
                romanceMovies,
                documentaries,
            }
        }
    } catch (e) {
        console.error(`Error! Fetching from api \n${e}`)
    }

    return {
        props: {}
    }
}

export default Home